version: "3"

services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PWD=${MYSQL_PWD}
    ports:
      - 3306:3306
      - 8080:8080
    volumes:
      - ./:/app