apiVersion: v1
kind: Service
metadata:
  labels:
    app: horty-api
  name: api-service
  namespace: bbhorty
spec:
  type: NodePort
  selector:
    app: horty-api
  ports:
    - nodePort: 30876
      port: 8080
      protocol: TCP
      targetPort: 8080

