apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: bbhorty
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '3000'
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
