apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bbhorty-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "back-ip-adress"
spec:
  rules:
    - host: api.bbhorty.ml
      http:
        paths:
          - path: /*
            backend:
              serviceName: api-service
              servicePort: 8080